name: Android CI/CD Debug

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  validate-update-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate update.json
        run: |
          # Periksa apakah file update.json ada
          if [ ! -f update.json ]; then
            echo "Error: update.json tidak ditemukan!"
            exit 1
          fi
          
          # Validasi struktur JSON
          VERSION=$(jq -r '.version // empty' update.json)
          DESCRIPTION=$(jq -r '.description // empty' update.json)
          
          # Cek apakah versi valid
          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Format versi tidak valid. Gunakan format x.y.z"
            exit 1
          fi
          
          # Cek deskripsi
          if [ -z "$DESCRIPTION" ]; then
            echo "Error: Deskripsi tidak boleh kosong"
            exit 1
          fi
          
          echo "Validasi update.json berhasil"

      - name: Debug Information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"

  build:
    needs: validate-update-json
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        run: |
          ./gradlew assembleRelease
          ls -l app/build/outputs/apk/release/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: volatoon-release-apk
          path: app/build/outputs/apk/release/*.apk
          retention-days: 5

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: volatoon-release-apk

      - name: Validate Release Conditions
        run: |
          # Cek apakah tag sesuai format
          if [[ ! "${{ github.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag tidak sesuai format. Gunakan v1.0.0"
            exit 1
          fi

      - name: Read update.json
        id: update_json
        run: |
          VERSION=$(jq -r '.version' update.json)
          DESCRIPTION=$(jq -r '.description' update.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "description=$DESCRIPTION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: '*.apk'
          body: |
            ## Volatoon Release ${{ steps.update_json.outputs.version }}
            ${{ steps.update_json.outputs.description }}
          draft: false
          prerelease: false